# Generated by Django 4.0.5 on 2022-06-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cust_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Occupation', models.CharField(max_length=50)),
                ('StartDate', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
    ]
